# Generated by Django 2.0.6 on 2018-06-05 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('filename', models.FileField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
    ]
