# Generated by Django 2.0.6 on 2018-06-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='filename',
            field=models.FileField(blank=True, default=None, max_length=1024, null=True, upload_to=''),
        ),
    ]
