# Generated by Django 2.0.6 on 2018-06-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0004_auto_20180605_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extracteddata',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='pdf',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='extracteddata',
            name='file',
            field=models.FileField(blank=True, default=None, max_length=1024, null=True, upload_to='extractor/'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(blank=True, default=None, max_length=1024, null=True, upload_to='extractor/'),
        ),
    ]
