# Generated by Django 2.0.6 on 2018-06-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0005_auto_20180606_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extracteddata',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='pdf',
            options={'ordering': ['created']},
        ),
    ]
